import React,{useState,useSyncExternalStore} from 'react';
import {createRoot} from 'react-dom/client';
import * as XLSX from 'xlsx';
import {crmStore,makeCode,makeId} from './store';
import {options} from './options';
import type {CrmState,Lead} from './types';
import {DataFoundation} from './phase1';
import {Pipeline,ProgressEntry} from './journey';
import './styles.css';

type View='home'|'progress'|'pipeline'|'lead'|'consultation'|'visit'|'sale'|'members'|'foundation'|'quality'|'export';
const today=()=>new Date().toISOString().slice(0,10);
const Field=({label,required,children}:{label:string;required?:boolean;children:React.ReactNode})=><label><span>{label}{required&&<b>필수</b>}</span>{children}</label>;
const Select=({name,items,required=true}:{name:string;items:readonly string[];required?:boolean})=><select name={name} required={required}><option value="">선택</option>{items.map(x=><option key={x}>{x}</option>)}</select>;

function App(){
 const data=useSyncExternalStore(crmStore.subscribe,crmStore.get); const [view,setView]=useState<View>('home');
 const nav:[View,string][]=[['home','홈'],['lead','신규 리드'],['progress','고객 응대·등록'],['pipeline','진행 중 고객'],['members','회원'],['foundation','상권·상품 DB'],['quality','데이터 품질'],['export','내보내기']];
 return <div className="shell"><aside><div className="brand"><small>1986 FITNESS WONHEUNG</small><strong>BI DATA CRM</strong><em>원천 데이터 수집 시스템</em></div><nav>{nav.map(([id,label])=><button className={view===id?'active':''} onClick={()=>setView(id)} key={id}>{label}</button>)}</nav><div className="storage">현재: <b>로컬 데모 세션</b><small>Supabase 연결 전 데이터는 새로고침 시 초기화됩니다.</small></div></aside><main><header><div><p>1986 FITNESS · 원흥점</p><h1>{nav.find(x=>x[0]===view)?.[1]}</h1></div><span className="badge">관리자 전용</span></header>{view==='home'&&<Home data={data} go={setView}/>} {view==='lead'&&<LeadForm data={data} done={()=>setView('pipeline')}/>} {view==='progress'&&<ProgressEntry data={data} done={()=>setView('pipeline')}/>} {view==='pipeline'&&<Pipeline data={data} openNew={()=>setView('lead')}/>} {view==='members'&&<Members data={data}/>} {view==='foundation'&&<DataFoundation data={data}/>} {view==='quality'&&<Quality data={data}/>} {view==='export'&&<Exports data={data}/>}</main></div>
}
function Home({data,go}:{data:CrmState;go:(v:View)=>void}){const month=today().slice(0,7);const cards=[['신규 리드',data.leads.filter(x=>x.firstContactDate.startsWith(month)).length],['상담',data.consultations.filter(x=>x.date.startsWith(month)).length],['방문',data.visits.filter(x=>x.actualDate?.startsWith(month)&&x.status==='방문완료').length],['등록',data.members.filter(x=>x.joinedAt.startsWith(month)).length]];return <><section className="notice"><div><b>좋은 BI는 좋은 DB에서 시작합니다.</b><p>신규 리드를 먼저 저장하고 상담·방문·등록은 한 화면에서 이어가세요.</p></div><button onClick={()=>go('lead')}>+ 신규 리드</button></section><section className="cards">{cards.map(([a,b])=><article key={a}><span>이번 달</span><strong>{b}</strong><p>{a}</p></article>)}</section><section className="panel"><div className="panelTitle"><h2>최근 입력 기록</h2><span>{data.leads.length}건</span></div>{data.leads.length?<table><thead><tr><th>유입일</th><th>이름</th><th>유입경로</th><th>상권</th><th>관심상품</th><th>상태</th></tr></thead><tbody>{data.leads.slice(0,8).map(x=><tr key={x.id}><td>{x.firstContactDate}</td><td>{x.name}</td><td>{x.source}</td><td>{data.apartments.find(a=>a.id===x.complexId)?.name||data.areas.find(a=>a.id===x.areaId)?.name||'미확인'}</td><td>{data.products.find(p=>p.id===x.interestedProductId)?.name||'미확인'}</td><td><i>{x.status}</i></td></tr>)}</tbody></table>:<Empty/>}</section></>}
const Empty=()=> <div className="empty"><strong>아직 입력된 데이터가 없습니다.</strong><p>첫 신규 리드부터 기록을 시작하세요.</p></div>;
function LeadForm({data,done}:{data:CrmState;done:()=>void}){return <FormCard title="신규 리드 기록" sub="최초 문의와 상권·상품 관심을 하나의 Journey로 연결합니다." onSubmit={fd=>{crmStore.add('leads',{id:makeId(),leadCode:makeCode('L',data.leads.length),firstContactDate:String(fd.get('date')),name:String(fd.get('name')),gender:String(fd.get('gender')),ageGroup:String(fd.get('age')),source:String(fd.get('source')),inquiryMethod:String(fd.get('method')),goal:String(fd.get('goal')),experience:String(fd.get('experience')),status:'신규',areaId:String(fd.get('area')||'')||undefined,complexId:String(fd.get('complex')||'')||undefined,interestedProductId:String(fd.get('product')||'')||undefined,note:String(fd.get('note')||''),createdAt:new Date().toISOString()});done()}}><Field label="최초 유입일" required><input type="date" name="date" defaultValue={today()} required/></Field><Field label="이름" required><input name="name" placeholder="실명 입력" required/></Field><Field label="성별" required><Select name="gender" items={options.genders}/></Field><Field label="연령대" required><Select name="age" items={options.ageGroups}/></Field><Field label="유입경로" required><Select name="source" items={options.sources}/></Field><Field label="최초 문의방식" required><Select name="method" items={options.inquiryMethods}/></Field><Field label="운동목적" required><Select name="goal" items={options.goals}/></Field><Field label="운동경험" required><Select name="experience" items={options.experience}/></Field><div className="formDivider"><b>상권·상품 연결</b><span>분석 가능한 경우만 선택하세요.</span></div><Field label="거주 지역"><select name="area"><option value="">미확인 / 선택 안 함</option>{data.areas.map(x=><option key={x.id} value={x.id}>{x.name} · {x.distanceBand}</option>)}</select></Field><Field label="아파트 단지"><select name="complex"><option value="">해당 없음 / 미확인</option>{data.apartments.map(x=><option key={x.id} value={x.id}>{x.name} · {data.areas.find(a=>a.id===x.areaId)?.name}</option>)}</select></Field><Field label="관심 상품"><select name="product"><option value="">미확인 / 선택 안 함</option>{data.products.filter(x=>x.status!=='판매종료').map(x=><option key={x.id} value={x.id}>{x.name} · {x.listPrice.toLocaleString()}원</option>)}</select></Field><Field label="메모"><textarea name="note" placeholder="필요한 맥락만 간단히 기록"/></Field></FormCard>}
function LeadPick({data}:{data:CrmState}){return <Select name="lead" items={data.leads.filter(x=>x.status!=='등록').map(x=>`${x.leadCode} · ${x.name}`)}/>}
const leadId=(v:string)=>v.split(' · ')[0]; const findLead=(data:CrmState,v:string)=>data.leads.find(x=>x.leadCode===leadId(v));
function ConsultForm({data,done}:{data:CrmState;done:()=>void}){return <FormCard title="상담 기록" sub="가격 반응과 선택·거절 맥락을 남깁니다." disabled={!data.leads.length} onSubmit={fd=>{const l=findLead(data,String(fd.get('lead')))!;crmStore.add('consultations',{id:makeId(),consultationCode:makeCode('C',data.consultations.length),leadId:l.id,date:String(fd.get('date')),consultant:String(fd.get('staff')),priceResistance:String(fd.get('price')),competitorStatus:String(fd.get('competitorStatus')),competitor:String(fd.get('competitor')||''),result:String(fd.get('result')),followUpNeeded:fd.get('follow')==='예',followUpDate:String(fd.get('followDate')||''),note:String(fd.get('note')||''),createdAt:new Date().toISOString()});l.status='상담완료';done()}}><Field label="리드" required><LeadPick data={data}/></Field><Field label="상담일" required><input type="date" name="date" defaultValue={today()} required/></Field><Field label="상담 담당자" required><input name="staff" required/></Field><Field label="가격 저항" required><Select name="price" items={options.priceResistance}/></Field><Field label="비교센터 여부" required><Select name="competitorStatus" items={['없음','있음','미확인']}/></Field><Field label="비교센터"><input name="competitor"/></Field><Field label="상담 결과" required><Select name="result" items={options.consultationResults}/></Field><Field label="후속상담 필요" required><Select name="follow" items={['예','아니오']}/></Field><Field label="후속상담 예정일"><input type="date" name="followDate"/></Field><Field label="상담 메모"><textarea name="note"/></Field></FormCard>}
function VisitForm({data,done}:{data:CrmState;done:()=>void}){return <FormCard title="방문 기록" sub="문의와 실제 방문을 구분합니다." disabled={!data.leads.length} onSubmit={fd=>{const l=findLead(data,String(fd.get('lead')))!;crmStore.add('visits',{id:makeId(),visitCode:makeCode('V',data.visits.length),leadId:l.id,scheduledDate:String(fd.get('scheduled')||''),actualDate:String(fd.get('actual')||''),type:String(fd.get('type')),status:String(fd.get('status')),staff:String(fd.get('staff')),tour:fd.get('tour')==='예',ptConsultation:fd.get('pt')==='예',trial:fd.get('trial')==='예',createdAt:new Date().toISOString()});l.status='방문예정';done()}}><Field label="리드" required><LeadPick data={data}/></Field><Field label="방문예정일"><input type="date" name="scheduled"/></Field><Field label="실제방문일"><input type="date" name="actual"/></Field><Field label="방문유형" required><Select name="type" items={options.visitTypes}/></Field><Field label="방문상태" required><Select name="status" items={options.visitStatuses}/></Field><Field label="응대 담당자" required><input name="staff" required/></Field><Field label="센터투어" required><Select name="tour" items={['예','아니오']}/></Field><Field label="PT 상담" required><Select name="pt" items={['예','아니오']}/></Field><Field label="체험" required><Select name="trial" items={['예','아니오']}/></Field></FormCard>}
function SaleForm({data,done}:{data:CrmState;done:()=>void}){return <FormCard title="등록 완료" sub="판매와 회원 생성을 한 번에 처리합니다." disabled={!data.leads.filter(x=>x.status!=='등록').length} onSubmit={fd=>{const l=findLead(data,String(fd.get('lead')))!;const memberId=makeId(),createdAt=new Date().toISOString();crmStore.add('members',{id:memberId,memberCode:makeCode('M',data.members.length),leadId:l.id,name:l.name,gender:l.gender,ageGroup:l.ageGroup,joinedAt:String(fd.get('date')),source:l.source,status:'이용중',areaId:l.areaId,complexId:l.complexId,createdAt});crmStore.add('sales',{id:makeId(),saleCode:makeCode('S',data.sales.length),leadId:l.id,memberId,paymentDate:String(fd.get('date')),product:String(fd.get('product')),productType:String(fd.get('type')),listPrice:Number(fd.get('listPrice')),amount:Number(fd.get('amount')),saleType:'신규',staff:String(fd.get('staff')),createdAt});l.status='등록';done()}}><Field label="리드" required><LeadPick data={data}/></Field><Field label="결제일" required><input type="date" name="date" defaultValue={today()} required/></Field><Field label="상품명" required><input name="product" required/></Field><Field label="상품구분" required><Select name="type" items={options.productTypes}/></Field><Field label="정상가격" required><input type="number" name="listPrice" min="0" required/></Field><Field label="실제결제금액" required><input type="number" name="amount" min="0" required/></Field><Field label="담당자" required><input name="staff" required/></Field></FormCard>}
function FormCard({title,sub,children,onSubmit,disabled}:{title:string;sub:string;children:React.ReactNode;onSubmit:(fd:FormData)=>void;disabled?:boolean}){return <section className="formCard"><div className="formHead"><div><h2>{title}</h2><p>{sub}</p></div><span>필수항목 우선</span></div>{disabled?<div className="empty"><strong>먼저 신규 리드를 입력하세요.</strong></div>:<form onSubmit={e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget))}}><div className="formGrid">{children}</div><div className="formActions"><button type="submit">저장하기</button></div></form>}</section>}
function Members({data}:{data:CrmState}){return <section className="panel"><div className="panelTitle"><h2>회원 목록</h2><span>{data.members.length}명</span></div>{data.members.length?<table><thead><tr><th>회원 ID</th><th>이름</th><th>최초등록일</th><th>유입경로</th><th>누적결제</th><th>상태</th></tr></thead><tbody>{data.members.map(m=><tr key={m.id}><td>{m.memberCode}</td><td><b>{m.name}</b></td><td>{m.joinedAt}</td><td>{m.source}</td><td>{data.sales.filter(s=>s.memberId===m.id).reduce((a,b)=>a+b.amount,0).toLocaleString()}원</td><td><i>{m.status}</i></td></tr>)}</tbody></table>:<Empty/>}</section>}
function Quality({data}:{data:CrmState}){const rows=[['가격저항 미입력',data.consultations.filter(x=>!x.priceResistance).length],['비교센터 상태 미입력',data.consultations.filter(x=>!x.competitorStatus).length],['상담 없는 리드',data.leads.filter(l=>!data.consultations.some(c=>c.leadId===l.id)).length],['방문결과 없는 리드',data.leads.filter(l=>!data.visits.some(v=>v.leadId===l.id)).length]];return <section className="panel"><div className="panelTitle"><h2>데이터 품질 확인</h2><span>누락 탐지</span></div><div className="quality">{rows.map(([x,n])=><div><span>{x}</span><strong className={n?'warn':''}>{n}건</strong></div>)}</div></section>}
function Exports({data}:{data:CrmState}){const exportXlsx=()=>{const wb=XLSX.utils.book_new();for(const [k,v] of Object.entries(data))XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(v),k.slice(0,31));XLSX.writeFile(wb,`1986_CRM_${today()}.xlsx`)};const exportJson=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=`1986_CRM_BACKUP_${today()}.json`;a.click()};return <section className="panel"><div className="panelTitle"><h2>데이터 내보내기</h2><span>Google Sheets 호환</span></div><div className="exports"><button onClick={exportXlsx}><b>XLSX 전체 내보내기</b><small>Entity별 시트로 저장</small></button><button onClick={exportJson}><b>JSON Backup</b><small>복구용 원본 구조</small></button></div><p className="hint">BI_MASTER는 Supabase 집계 View 연결 단계에서 추가됩니다.</p></section>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
