import React,{useState} from 'react';
import type {CrmState} from './types';
import {crmStore,makeCode,makeId} from './store';
import {options} from './options';

const today=()=>new Date().toISOString().slice(0,10);
const F=({label,children}:{label:string;children:React.ReactNode})=><label><span>{label}<b>필수</b></span>{children}</label>;
const O=({label,children}:{label:string;children:React.ReactNode})=><label><span>{label}</span>{children}</label>;
const S=({name,items}:{name:string;items:readonly string[]})=><select name={name} required><option value="">선택</option>{items.map(x=><option key={x}>{x}</option>)}</select>;

type Master='area'|'apartment'|'product'|'competitor'|'poi';
export function DataFoundation({data}:{data:CrmState}){
 const [tab,setTab]=useState<Master>('area');
 const tabs:[Master,string][]=[['area','지역'],['apartment','아파트'],['product','상품'],['competitor','경쟁사'],['poi','POI']];
 return <><section className="masterIntro"><div><span>PHASE 1 · DATA FOUNDATION</span><h2>상권과 상품의 기준정보</h2><p>표기가 흩어지지 않도록 먼저 Master를 등록하고 고객·매출 데이터에서 선택합니다.</p></div><div className="confidenceLegend"><b>외부 데이터 신뢰도</b><span>A 공식통계 · B 업체공식 · C 공개자료 · D 추정</span></div></section><div className="masterTabs">{tabs.map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>{tab==='area'&&<AreaForm data={data}/>} {tab==='apartment'&&<ApartmentForm data={data}/>} {tab==='product'&&<ProductForm data={data}/>} {tab==='competitor'&&<CompetitorForm data={data}/>} {tab==='poi'&&<PoiForm data={data}/>}</>
}
function Card({title,description,count,children,rows}:{title:string;description:string;count:number;children:React.ReactNode;rows:React.ReactNode}){return <div className="masterLayout"><section className="formCard"><div className="formHead"><div><h2>{title}</h2><p>{description}</p></div><span>필수항목 우선</span></div>{children}</section><section className="panel masterList"><div className="panelTitle"><h2>등록 목록</h2><span>{count}건</span></div>{count?<div className="masterRows">{rows}</div>:<div className="empty"><strong>등록된 기준정보가 없습니다.</strong></div>}</section></div>}
const Form=({children,onSubmit}:{children:React.ReactNode;onSubmit:(fd:FormData)=>void})=><form onSubmit={e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget));e.currentTarget.reset()}}><div className="formGrid">{children}</div><div className="formActions"><button>저장하기</button></div></form>;
const Row=({title,meta,value}:{title:string;meta:string;value:string})=><div className="masterRow"><div><b>{title}</b><small>{meta}</small></div><strong>{value}</strong></div>;
function AreaForm({data}:{data:CrmState}){return <Card title="지역 Master" description="행정동·생활권·거리구간을 표준화합니다." count={data.areas.length} rows={data.areas.map(x=><Row key={x.id} title={x.name} meta={`${x.adminDong} · ${x.distanceBand} · 신뢰도 ${x.confidenceGrade}`} value={x.marketGrade}/>) }><Form onSubmit={fd=>crmStore.add('areas',{id:makeId(),areaCode:makeCode('A',data.areas.length),name:String(fd.get('name')),type:String(fd.get('type')),marketGrade:String(fd.get('grade')),adminDong:String(fd.get('adminDong')),legalDong:String(fd.get('legalDong')||''),distanceBand:String(fd.get('distance')),centerDistanceKm:Number(fd.get('km'))||undefined,households:Number(fd.get('households'))||undefined,population2040:Number(fd.get('population2040'))||undefined,competitorCount:Number(fd.get('competitors'))||undefined,confidenceGrade:String(fd.get('confidence')),source:String(fd.get('source')),referenceDate:String(fd.get('referenceDate')),createdAt:new Date().toISOString()})}><F label="지역명"><input name="name" required placeholder="예: 도래울 생활권"/></F><F label="지역유형"><S name="type" items={options.areaTypes}/></F><F label="상권등급"><S name="grade" items={options.marketGrades}/></F><F label="행정동"><input name="adminDong" required/></F><O label="법정동"><input name="legalDong"/></O><F label="거리구간"><S name="distance" items={options.distanceBands}/></F><O label="센터 거리(km)"><input name="km" type="number" min="0" step="0.1"/></O><O label="전체 세대수"><input name="households" type="number" min="0"/></O><O label="20–40대 인구"><input name="population2040" type="number" min="0"/></O><O label="경쟁센터 수"><input name="competitors" type="number" min="0"/></O><F label="데이터 기준일"><input name="referenceDate" type="date" defaultValue={today()} required/></F><F label="신뢰도"><S name="confidence" items={options.confidenceGrades}/></F><F label="출처"><input name="source" required placeholder="예: KOSIS 2026-07"/></F></Form></Card>}
function ApartmentForm({data}:{data:CrmState}){return <Card title="아파트 Master" description="아파트 표기를 하나의 단지 ID로 통일합니다." count={data.apartments.length} rows={data.apartments.map(x=><Row key={x.id} title={x.name} meta={`${data.areas.find(a=>a.id===x.areaId)?.name||'지역 미지정'} · ${x.households.toLocaleString()}세대`} value={x.marketingStatus}/>) }><Form onSubmit={fd=>crmStore.add('apartments',{id:makeId(),complexCode:makeCode('AP',data.apartments.length),name:String(fd.get('name')),areaId:String(fd.get('area')),households:Number(fd.get('households')),buildingCount:Number(fd.get('buildings'))||undefined,completionYear:Number(fd.get('year'))||undefined,centerDistanceKm:Number(fd.get('km'))||undefined,walkingMinutes:Number(fd.get('walk'))||undefined,nearestStation:String(fd.get('station')||''),marketingStatus:String(fd.get('marketing')),confidenceGrade:String(fd.get('confidence')),source:String(fd.get('source')),referenceDate:String(fd.get('referenceDate')),createdAt:new Date().toISOString()})}><F label="단지명"><input name="name" required/></F><F label="지역"><select name="area" required><option value="">선택</option>{data.areas.map(x=><option value={x.id}>{x.name}</option>)}</select></F><F label="세대수"><input name="households" type="number" min="1" required/></F><O label="동 수"><input name="buildings" type="number" min="1"/></O><O label="준공연도"><input name="year" type="number" min="1900" max="2100"/></O><O label="센터 거리(km)"><input name="km" type="number" min="0" step="0.1"/></O><O label="도보 시간(분)"><input name="walk" type="number" min="0"/></O><O label="인접역"><input name="station"/></O><F label="마케팅 상태"><S name="marketing" items={options.marketingStatuses}/></F><F label="데이터 기준일"><input name="referenceDate" type="date" defaultValue={today()} required/></F><F label="신뢰도"><S name="confidence" items={options.confidenceGrades}/></F><F label="출처"><input name="source" required/></F></Form></Card>}
function ProductForm({data}:{data:CrmState}){return <Card title="상품·가격 Master" description="가격 변경 이력을 덮어쓰지 않고 새 상품 버전으로 저장합니다." count={data.products.length} rows={data.products.map(x=><Row key={x.id} title={x.name} meta={`${x.category} · ${x.startsOn}부터`} value={`${x.listPrice.toLocaleString()}원`}/>) }><Form onSubmit={fd=>crmStore.add('products',{id:makeId(),productCode:makeCode('P',data.products.length),category:String(fd.get('category')),name:String(fd.get('name')),durationMonths:Number(fd.get('duration'))||undefined,ptSessions:Number(fd.get('sessions'))||undefined,listPrice:Number(fd.get('price')),variableCost:Number(fd.get('cost'))||undefined,startsOn:String(fd.get('starts')),endsOn:String(fd.get('ends')||''),status:String(fd.get('status')),createdAt:new Date().toISOString()})}><F label="상품명"><input name="name" required/></F><F label="상품구분"><S name="category" items={options.productTypes}/></F><O label="회원권 기간(개월)"><input name="duration" type="number" min="1"/></O><O label="PT 횟수"><input name="sessions" type="number" min="1"/></O><F label="정상가격"><input name="price" type="number" min="0" required/></F><O label="변동원가"><input name="cost" type="number" min="0"/></O><F label="판매 시작일"><input name="starts" type="date" defaultValue={today()} required/></F><O label="판매 종료일"><input name="ends" type="date"/></O><F label="판매상태"><S name="status" items={['판매예정','판매중','판매종료']}/></F></Form></Card>}
function CompetitorForm({data}:{data:CrmState}){return <Card title="경쟁사 Master" description="확인한 사실만 기록하고 미확인 값은 비워둡니다." count={data.competitors.length} rows={data.competitors.map(x=><Row key={x.id} title={x.name} meta={`${x.position} · ${x.centerDistanceKm??'-'}km · 신뢰도 ${x.confidenceGrade}`} value={x.status}/>) }><Form onSubmit={fd=>crmStore.add('competitors',{id:makeId(),competitorCode:makeCode('CP',data.competitors.length),name:String(fd.get('name')),areaId:String(fd.get('area')||''),status:String(fd.get('status')),businessType:String(fd.get('businessType')),position:String(fd.get('position')),centerDistanceKm:Number(fd.get('km'))||undefined,is24h:fd.get('is24h')==='예',facilitySizeSqm:Number(fd.get('size'))||undefined,reviewCount:Number(fd.get('reviews'))||undefined,rating:Number(fd.get('rating'))||undefined,mainMessage:String(fd.get('message')||''),confidenceGrade:String(fd.get('confidence')),source:String(fd.get('source')),lastChecked:String(fd.get('checked')),createdAt:new Date().toISOString()})}><F label="센터명"><input name="name" required/></F><O label="지역"><select name="area"><option value="">미지정</option>{data.areas.map(x=><option value={x.id}>{x.name}</option>)}</select></O><F label="상태"><S name="status" items={['영업중','오픈예정','폐업예정','영업종료','확인필요']}/></F><F label="업태"><input name="businessType" required placeholder="헬스·PT·24시 등"/></F><F label="포지션"><S name="position" items={['초저가','저가','중저가','중가','중고가','고가','시설중심','PT중심','기타']}/></F><O label="센터 거리(km)"><input name="km" type="number" min="0" step="0.1"/></O><F label="24시간 여부"><S name="is24h" items={['예','아니오']}/></F><O label="시설면적(㎡)"><input name="size" type="number" min="0"/></O><O label="리뷰 수"><input name="reviews" type="number" min="0"/></O><O label="평점"><input name="rating" type="number" min="0" max="5" step="0.1"/></O><O label="핵심 홍보문구"><input name="message"/></O><F label="최종 확인일"><input name="checked" type="date" defaultValue={today()} required/></F><F label="신뢰도"><S name="confidence" items={options.confidenceGrades}/></F><F label="출처"><input name="source" required/></F></Form></Card>}
function PoiForm({data}:{data:CrmState}){return <Card title="POI Master" description="기업·학교·상업시설 등 잠재수요 발생시설을 관리합니다." count={data.pois.length} rows={data.pois.map(x=><Row key={x.id} title={x.name} meta={`${x.category} · ${data.areas.find(a=>a.id===x.areaId)?.name||'-'}`} value={x.partnershipStatus}/>) }><Form onSubmit={fd=>crmStore.add('pois',{id:makeId(),poiCode:makeCode('POI',data.pois.length),name:String(fd.get('name')),category:String(fd.get('category')),areaId:String(fd.get('area')),estimatedPopulation:Number(fd.get('population'))||undefined,employeeCount:Number(fd.get('employees'))||undefined,visitorVolume:Number(fd.get('visitors'))||undefined,partnershipStatus:String(fd.get('partnership')),confidenceGrade:String(fd.get('confidence')),source:String(fd.get('source')),lastChecked:String(fd.get('checked')),createdAt:new Date().toISOString()})}><F label="시설명"><input name="name" required/></F><F label="분류"><S name="category" items={options.poiCategories}/></F><F label="지역"><select name="area" required><option value="">선택</option>{data.areas.map(x=><option value={x.id}>{x.name}</option>)}</select></F><O label="추정 이용인구"><input name="population" type="number" min="0"/></O><O label="직원 수"><input name="employees" type="number" min="0"/></O><O label="유동량"><input name="visitors" type="number" min="0"/></O><F label="제휴상태"><S name="partnership" items={options.partnershipStatuses}/></F><F label="최종 확인일"><input name="checked" type="date" defaultValue={today()} required/></F><F label="신뢰도"><S name="confidence" items={options.confidenceGrades}/></F><F label="출처"><input name="source" required/></F></Form></Card>}
