export type Id = string;
export type LeadStatus = '신규'|'상담예정'|'상담완료'|'방문예정'|'등록'|'보류'|'미등록'|'연락두절';
export interface Lead { id:Id; leadCode:string; firstContactDate:string; name:string; gender:string; ageGroup:string; source:string; inquiryMethod:string; goal:string; experience:string; status:LeadStatus; campaign?:string; note?:string; createdAt:string }
export interface Consultation { id:Id; consultationCode:string; leadId:Id; date:string; consultant:string; priceResistance:string; competitorStatus:string; competitor?:string; result:string; followUpNeeded:boolean; followUpDate?:string; note?:string; createdAt:string }
export interface Visit { id:Id; visitCode:string; leadId:Id; scheduledDate?:string; actualDate?:string; type:string; status:string; staff:string; tour:boolean; ptConsultation:boolean; trial:boolean; createdAt:string }
export interface Sale { id:Id; saleCode:string; leadId:Id; memberId:Id; paymentDate:string; product:string; productType:string; listPrice:number; amount:number; saleType:string; staff:string; createdAt:string }
export interface Member { id:Id; memberCode:string; leadId:Id; name:string; gender:string; ageGroup:string; joinedAt:string; source:string; status:string; createdAt:string }
export interface Product { id:Id; productCode:string; category:string; name:string; durationMonths?:number; ptSessions?:number; listPrice:number; variableCost?:number; startsOn:string; endsOn?:string; status:string; createdAt:string }
export interface Area { id:Id; areaCode:string; name:string; type:string; marketGrade:string; adminDong:string; legalDong?:string; distanceBand:string; centerDistanceKm?:number; households?:number; population2040?:number; competitorCount?:number; confidenceGrade:string; source:string; referenceDate:string; createdAt:string }
export interface Apartment { id:Id; complexCode:string; name:string; areaId:Id; households:number; buildingCount?:number; completionYear?:number; centerDistanceKm?:number; walkingMinutes?:number; nearestStation?:string; marketingStatus:string; confidenceGrade:string; source:string; referenceDate:string; createdAt:string }
export interface Competitor { id:Id; competitorCode:string; name:string; areaId?:Id; status:string; businessType:string; position:string; centerDistanceKm?:number; is24h:boolean; facilitySizeSqm?:number; reviewCount?:number; rating?:number; mainMessage?:string; confidenceGrade:string; source:string; lastChecked:string; createdAt:string }
export interface Poi { id:Id; poiCode:string; name:string; category:string; areaId:Id; estimatedPopulation?:number; employeeCount?:number; visitorVolume?:number; partnershipStatus:string; confidenceGrade:string; source:string; lastChecked:string; createdAt:string }
export interface CrmState { leads:Lead[]; consultations:Consultation[]; visits:Visit[]; sales:Sale[]; members:Member[]; products:Product[]; areas:Area[]; apartments:Apartment[]; competitors:Competitor[]; pois:Poi[] }
